apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvcs
  namespace: my-app  # Specify your desired namespace
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi  # The size of the storage you want to request
  storageClassName: longhorn  # Use Longhorn as the storage class
