apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvcs
  namespace: my-app  # Specify your desired namespace
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi  # The size of the storage you want to request
  storageClassName: nfs  # Use Longhorn as the storage class
