apiVersion: apps/v1
kind: Deployment
metadata:
  name: calculator
  namespace: my-app
spec:
  replicas: 10
  selector:
    matchLabels:
      app: calculator
  template:
    metadata:
      labels:
        app: calculator
    spec:
      containers:
      - name: calculator
        image: soundar4336/calculator-app:latest
        ports:
        - containerPort: 8501
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        volumeMounts:
        - name: calculator-storage
          mountPath: /data  # Path inside the container where the volume will be mounted
      volumes:
      - name: calculator-storage
        persistentVolumeClaim:
          claimName: pvc  # Reference to the PVC that was created
