apiVersion: v1
kind: Service
metadata:
  name: calculator-service
  namespace: my-app
spec:
  selector:
    app: calculator
  ports:
    - protocol: TCP
      port: 8501
      targetPort: 8501
  type: ClusterIP